"base_path" : "BASE_PATH"
"production_url" : "PRODUCTION_URL"

"pages" :
  "permalink" : '/:relative_path/:filename'
  "sort" : ["position", "asc"]
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"lab" :
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"_root" :
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"files" :
  "use" : "static"
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"readings" :
  "use" : "static"
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"lectures" :
  "use" : "static"
  "exclude" : "eot$"
  "paginator" :
    "enable" : "false"
  "rss" :
    "enable" : "false"

"widgets" :
  "analytics" :
    "use" : "google"
    "tracking_id" : "UA-55655322-1"
  "syntax" :
    "use" : "prettify"
    "linenums" : "false"
    "cdn" : "false"
